### ISSUE TITLE
Why doc._.trf_all_hidden_states returns 'None' ?

### ISSUE THREAD

**Issue by zhongkaifu** [explosion/spacy-transformers#101]
Hi, 

I tried the example in this website, however, "print(doc._.trf_all_hidden_states)" returns "None". Did you know why ? In addition, is there any way I can get hidden states of any specified layer ? such as the last second layer. Thanks in advance.

>>> print(doc._.trf_word_pieces_)
['[CLS]', 'apple', 'shares', 'rose', 'on', 'the', 'news', '.', '[SEP]', '[CLS]', 'apple', 'pie', 'is', 'delicious', '.', '[SEP]']
>>> print(doc._.trf_last_hidden_state)
[[ 0.3435621  -0.23586848 -0.06684111 ... -0.17081814  0.60623384
   0.15930396]
 [ 0.6500827   0.01991945 -0.11502086 ... -0.5832423  -0.02782643
  -0.41220787]
 [ 1.4996121   0.02532512  0.23262474 ... -0.32126796  0.276052
   0.18531922]
 ...
 [-0.02583013 -0.13098243 -0.12244213 ... -0.09058861 -0.49521574
  -0.5967784 ]
 [ 0.2895408   0.01292455 -0.31585672 ...  0.33117494 -0.30976805
  -0.64231867]
 [ 0.2731962  -0.00716546 -0.00868208 ...  0.2674848  -0.5590836
  -0.4759428 ]]
>>> print(doc._.trf_all_hidden_states)
None
>>>

**Comment by ErnstDinkelmann** [comment]
Hi

Thanks for the amazing library.

Would also really like this functionality to work. See it known that it's an issue as per the docs.
But I imagine for a simple classifier that does feature extracting, combining more hidden states rather than just the last one, would improve classification results.

Any update here?

**Comment by svlandeg** [comment]
Hi @zhongkaifu : which example did you run exactly, can you share the command / script and the full output ?

**Comment by chikubee** [comment]
@zhongkaifu Could you fix that., I am getting None as well.

**Comment by sergicastellasape** [comment]
+1! trying to access the hidden states returns `None`. What's the status of this issue, is anyone working on it? (if a fix is on track soon I can wait for it but otherwise I'll start my own implementation!)

**Comment by cbiehl** [comment]
Please correct me if I'm wrong, but I think you can [access the hidden states / the output of the transformer model in the `TransformersWrapper.make_activations()` method](https://github.com/cbiehl/spacy-transformers/commit/87868b4d817ae852b842e05a198bcfc3ba1fefa0#diff-c435624dc949b0ac2601b8b3586d33e0) and then [set the attributes `trf_all_hidden_states` and `trf_all_activations` in the `TransformersTok2Vec.set_annotations()` method](https://github.com/cbiehl/spacy-transformers/commit/18005de1762123491e1fc181c646d7d2b5bd5e86#diff-7780512f07cc1f6db9f99c8c8c770be8).

**Comment by svlandeg** [comment]
I think this issue is not relevant anymore after the rewrite and recent publication of v1.0. I'll close this for now. 

New bugs can be opened on the [spaCy GitHub tracker](https://github.com/explosion/spaCy/issues) and feature requests or ask for coding help can be posted on the [spaCy discussions forum](https://github.com/explosion/spaCy/discussions).

Thanks all for testing the early prereleases of this package! All the feedback has been really helpful :-)
