### ISSUE TITLE
Can I freeze the update of pretrained weights

### ISSUE THREAD

**Issue by bastia1989** [explosion/spacy-transformers#124]
Say, if my training samples are not enough to do a end-to-end fine tuning, and I just want to fine tune the toppest text classification layer, i.e., the linear network, above the pretrained layers. Can I stop updating the pretrained weights imported from `en_trf_bertbaseuncased_lg`? Like discussed [here](https://github.com/huggingface/transformers/issues/400) in Hugging Face transformers.

**Comment by lamthuy** [comment]
You should try this: 
```
 model = spacy.load('en_trf_bertbaseuncased_lg')
 for param in model.get_pipe('trf_tok2vec').transformers_model.parameters():
            param.requires_grad = False
```

**Comment by svlandeg** [comment]
This use-case will be much better supported in the new version 1.0 of this library which works with spaCy 3.0. 

In a nutshell, you'll be able to "freeze" components so that the training loop still runs then, but doesn't update them. See [here](https://nightly.spacy.io/usage/training#config-components) for more details.

I'll go ahead and close this issue, as we're also moving support to the spaCy repo. New bugs can be opened on the [spaCy GitHub tracker](https://github.com/explosion/spaCy/issues) and feature requests or ask for coding help can be posted on the [spaCy discussions forum](https://github.com/explosion/spaCy/discussions)!
