### ISSUE TITLE
can't access some extensions

### ISSUE THREAD

**Issue by AnzorGozalishvili** [explosion/spacy-transformers#149]
I loaded model
```python
nlp = spacy.load("en_trf_bertbaseuncased_lg")
```
And I am trying to get values:
```python
    doc._.trf_all_hidden_states
    doc._.all_attentions
    doc._.trf_d_last_hidden_state
    doc._.trf_d_pooler_output
    doc._.trf_d_all_hidden_states
    doc._.trf_d_all_attentions
```
I am getting None or empty list for some of them and (doc._.all_attentions, doc._.trf_d_all_attentions) raises error AttributeError: [E046] can't retrieve unregistered attribute "all_extensions".

**Comment by adrianeboyd** [comment]
The `.all_attentions` in the README was a typo, thanks for pointing that out! It should be `.trf_all_attentions` like the other extensions. The `.trf_d_` extensions are only used if you're fine-tuning, and it looks like the basic framework for `.trf_all_hidden_states` and `.trf_all_attentions` is there but they just haven't been implemented yet.

The README has just been updated accordingly and you can see a bit of discussion about `all_hidden_states` and `all_attentions` in #101, in particular this comment: https://github.com/explosion/spacy-transformers/issues/101#issuecomment-576640861. I think the main issue here is making sure this code works correctly for all the different types of models that are supported by `spacy-transformers`, since there's some variation in terms of which values are returned beyond `last_hidden_state`.
