### ISSUE TITLE
Loading fine-tuned BERT model for classification

### ISSUE THREAD

**Issue by spatiebalk** [explosion/spacy-transformers#167]
I have fine-tuned a BERT base model for classifying text using [BertForSequenceClassification](https://huggingface.co/transformers/v2.2.0/model_doc/bert.html#bertforsequenceclassification) of transformers and I have saved this model  (directory contains config.json, pytorch_model.bin, special_tokens_map.json, tokenizer_config.json, vocab.txt). 

Now I want to load this model using spacy-transformers such that the model will be loaded as a Spacy model, as I want to use it later in an activate learning loop with Prodigy. However, I haven't been able to do this. 

Loading the model with:

`nlp = TransformersLanguage(trf_name=name, meta={"lang": "en"})
nlp.add_pipe(nlp.create_pipe("sentencizer"))
nlp.add_pipe(TransformersWordPiecer.from_pretrained(nlp.vocab, path))
nlp.add_pipe(TransformersTok2Vec.from_pretrained(nlp.vocab, path))`

doesn't load the final classifying layer (looking at the output of `print(nlp.pipe_names)`) but I don't know what to add/change.

So, I am wondering whether this is possible or I should train my model again with spacy-transformers.

**Comment by svlandeg** [comment]
Could you show the log output of that code snippet? Is an error/warning being thrown?

**Comment by spatiebalk** [comment]
I saved the model as:

`import transformers
model_to_save.save_pretrained(output_dir)
tokenizer.save_pretrained(output_dir)`

and tried to load it with: 
`from spacy_transformers import TransformersLanguage, TransformersWordPiecer, TransformersTok2Vec

nlp = TransformersLanguage(trf_name=name, meta={"lang": "en"})
nlp.add_pipe(nlp.create_pipe("sentencizer"))
nlp.add_pipe(TransformersWordPiecer.from_pretrained(nlp.vocab, path))
nlp.add_pipe(TransformersTok2Vec.from_pretrained(nlp.vocab, path))
`
Printing nlp.pipe_names gives: ['sentencizer', 'trf_wordpiecer', 'trf_tok2vec']
leading me to believe that the final classifying layer is not loaded. There is no error/warning, but it also doesn't give the desired result.

**Comment by svlandeg** [comment]
Apologies for the late follow-up.

The prerelease of this library had some issues with serialization, but I think all of that should be fixed in the new 1.0 release that works with the new spacy 3.0.

It would be great if you could upgrade and let us know how you go on the [spaCy discussions forum](https://github.com/explosion/spaCy/discussions). Bugs can be posted on the [spaCy GitHub tracker](https://github.com/explosion/spaCy/issues). 

Thanks for testing the early prereleases of this package! All the feedback has been really helpful :-)
