### ISSUE TITLE
Use sliding window to embed long sequences

### ISSUE THREAD

**Issue by connorbrinton** [explosion/spacy-transformers#17]
While most Transformer-based deep learning models have maximum sequence lengths, batching techniques have been developed to embed long sequences while maintaining context. The approach works by splitting long sequences using a sliding window, embedding each sequence, then choosing the maximum-context vector for each wordpiece. The approach as implemented in BERT is [available here](https://github.com/google-research/bert/blob/master/run_squad.py#L383), and a comparable implementation in AllenNLP is [available here](https://github.com/allenai/allennlp/pull/2537).

It would be great to have this approach implemented for all models in `spacy-pytorch-transformers`, so long documents could be embedded without truncation.

Thanks for creating this package! 😄

**Comment by honnibal** [comment]
I was thinking of doing this already! Glad to hear others have tried it.

If you want to write the function, have a look at the `foreach_sentences` function in `tok2vec.py`. We just need to do a similar transform, but with overlaps.

**Comment by connorbrinton** [comment]
Awesome! I don't have the bandwidth (or PyTorch expertise) to implement it right now, but if we start using `spacy-pytorch-transformers` where I work, this will be the first step I'll work on 🙂

**Comment by dscripka** [comment]
Sorry, to bring this issue back up, but I have a similar interest in embedding long sequences, and I'm struggling to understand how this is currently handled internally. From what I can tell from the documentation and the `foreach_sentences` functions (now in `model_registry.py`?)  it seems like Spacy just gets the contextual embedding for each token using the containing sentence as context:

```Internally, the transformer model will predict over sentences, and the resulting tensor features will be reconstructed to produce document-level annotations.```

If I understand that correctly, the expected behavior for the following scenario is:

```
nlp = spacy.load("en_pytt_robertabase_lg")
txt1 = "Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services."
txt2 = "Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four tech companies along with Amazon, Google, and Facebook."
doc1 = nlp(txt1)
doc2 = nlp(txt2)

print(doc1[-2], doc2[29]) # "services" in both docs
np.all(doc1.tensor[-2] == doc2.tensor[29]) # returns True
```

However, I've noticed that this behavior is not consistent. Here is an another example where the behavior appears to be different:

```
nlp = spacy.load("en_pytt_robertabase_lg")
txt1 = "As the market for personal computers expanded and evolved through the 1990s, Apple lost market share to the lower-priced duopoly of Microsoft Windows on Intel PC clones."
txt2 = "As the market for personal computers expanded and evolved through the 1990s, Apple lost market share to the lower-priced duopoly of Microsoft Windows on Intel PC clones. The board recruited CEO Gil Amelio to what would be a 500-day charge for him to rehabilitate the financially troubled company—reshaping it with layoffs, executive restructuring, and product focus."
doc1 = nlp(txt1)
doc2 = nlp(txt2)

print(doc1[-2], doc2[29]) # "clones" in both docs
np.all(doc1.tensor[-2] == doc2.tensor[29]) # returns False
```

More broadly, I'm interested in token-tagging applications where context across sentence boundaries is important, so a solution similar to the one suggested by @connorbrinton would be very useful. However, I wanted to make sure that I understood the current implementation first.

**Comment by svlandeg** [comment]
Apologies for the late follow-up.

Since this post, the library has been significantly rewritten and published today as v. 1.0 🥳 

New bugs can be opened on the [spaCy GitHub tracker](https://github.com/explosion/spaCy/issues) and feature requests or ask for coding help can be posted on the [spaCy discussions forum](https://github.com/explosion/spaCy/discussions)!
