### ISSUE TITLE
any plan on implementing ._.trf_all_attentions?

### ISSUE THREAD

**Issue by vr25** [explosion/spacy-transformers#174]
Hi,

Any plan on implementing ._.trf_all_attentions anytime soon? (The all_attentions output from the transformers model)

Thanks!

**Comment by adrianeboyd** [comment]
Sorry for the late reponse! We don't have plans to implement this for the current version because we're working on a complete rewrite using the upcoming spacy v3 that doesn't require as much explicit wrapping to access the underlying `transformers` data (you can see the progress in the branch `feature/spacy-v3`).

**Comment by adrianeboyd** [comment]
Should have added a better link: #173.
