### ISSUE TITLE
Import of bert-base-multilingual-cased limited to less than 512 Token

### ISSUE THREAD

**Issue by gullibleretorted** [explosion/spacy-transformers#222]
Hi there,

I am currently working on a binary text classifcation (mainly german language) problem and I have build a spaCy pipeline for that. In order to evaluate which model performs best for my task I have compared several pretrained models from the spacy library. So far, the multi-language Modell (xx_ent_wiki_sm) has achieved by far the best results. Therefore, I would now like to test the "big" bert-base-multilingual-cased modell.

To do that, I downloaded the bert-base-multilingual-cased tf-checkpoint and converted it to a pytorch model with the convert_bert_original_tf_checkpoint_to_pytorch.py script (https://github.com/huggingface/transformers/blob/master/src/transformers/convert_bert_original_tf_checkpoint_to_pytorch.py). After that I was able to "load this pyTorch model from the dedicated path" (https://github.com/explosion/spacy-transformers) to my pipeline.

The problem arrises, when I start the training with the same training data, as I used with the models (limited to 512 tokens) I get the error message:
```
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py in embedding(input, weight, padding_idx, max_norm, norm_type, scale_grad_by_freq, sparse)
1812 # remove once script supports set_grad_enabled
1813 _no_grad_embeddingrenorm(weight, input, max_norm, norm_type)
-> 1814 return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
1815
1816

IndexError: index out of range in self
```

After researching this problem and adjusting my length of my data input my only track at the moment is, that if I reduce the my input size below 256 words, it is working fine. I tried to adjust my config file in different manners (see optimizers adjustements in code below) to get the training done - without success.

Does someone have an idea or a clue, how I could fix that problem? Any idea would be highly appreciated!

Thanks a lot in advance!

```
`with nlp.disable_pipes(*other_pipes):  # only train textcat
        optimizer = nlp.begin_training()
        optimizer.token_vector_width = 512
        optimizer.embed_size = 150000  
        optimizer.hidden_width = 512
        print("Training the model...")
        print("{:^5}\t{:^5}\t{:^5}\t{:^5}".format("LOSS", "P", "R", "F"))
        batch_sizes = compounding(4.0, 32.0, 1.001)

        results = pd.DataFrame(index=np.arange(n_iter), columns=["textcat_p", "textcat_r", "textcat_f", "textcat_l"], )
        
        for i in range(n_iter):
            losses = {}
            # batch up the examples using spaCy's minibatch
            random.shuffle(train_data)
            batches = minibatch(train_data, size=batch_sizes)
            for batch in batches:
                texts, annotations = zip(*batch)
                nlp.update(texts, annotations, sgd=optimizer, drop=0.2, losses=losses)`
```

## Your Environment
* Python Version Used: 3.6
* spaCy Version Used: 2.3.2
* spaCy-transformers Version Used: 0.6.2

**Comment by adrianeboyd** [comment]
What version of pytorch are you using? We've run into a similar problem and think we might have tracked it down to a bug in pytorch 1.6.0. If you're using 1.6.0, try 1.5.1 instead, also for the model conversion step, which is where the bug might be affecting how the model is saved. We're still not entirely sure this is the problem, so let us know if it makes a difference for your example?

**Comment by gullibleretorted** [comment]
Hi there, 

thanks for the fast reply. I was indeed using pytorch 1.6.0 for both converting as well as training. As suggested, I tried both steps with pytorch 1.5.1 now, unfortunately with the same result :/

**Comment by adrianeboyd** [comment]
Thanks for the feedback, it may well not be the same error. Ah, and I realized I'm getting mixed up between versions here, too, since we've mainly been working with a newer version of `spacy-transformers` internally.

If you'd like, please try out `spacy-nightly` (with the new rewritten `spacy-transformers` v1.0, current release is v1.0.0rc0) to see if it is easier to get working. There's a sample textcat project you can start with using `python -m spacy project clone tutorials/textcat_goemotions` with a sample config using BERT, see the README: https://github.com/explosion/projects/tree/v3/tutorials/textcat_goemotions . The spacy docs are here: https://nightly.spacy.io, transformers info here: https://nightly.spacy.io/usage/embeddings-transformers#transformers

I also think you should be able to get started with the pytorch version of `bert-base-multilingual-cased` from the transformers models? I'm not sure why you're converting the tf model in the first place? This is something we haven't tested much...

**Comment by gullibleretorted** [comment]
Ahh I see - yeah, I read about it today and I will read into spacy-nightly in the next couple of hours. It seems pretty nice!:)

Regarding your last point: Yes, I also tried that with the links specific in that discussion (https://stackoverflow.com/questions/59701981/bert-tokenizer-model-download) and the vocab of the tf checkpoint. Nevertheless, I am getting the same error message as mentioned in the initial message.

**Comment by svlandeg** [comment]
Hi @gullibleretorted, I hope you find the new version 1.0 in combination with the new spaCy 3.0 more friendly to use! 

I'm not sure we'll be able to invest more resources to debug issues in the prereleases of this library, especially because it's been significantly rewritten and improved since your original post. We're also going to move the support to the spaCy repo. It would be great if you could upgrade and let us know how you go on the [spaCy discussions forum](https://github.com/explosion/spaCy/discussions)! Bugs can be posted on the [spaCy GitHub tracker](https://github.com/explosion/spaCy/issues).
