### ISSUE TITLE
Multi-language pipelines not available

### ISSUE THREAD

**Issue by danielcamara** [explosion/spacy-transformers#237]
Hi, 
I am interested in using the multilanguage pipeline with spacy-transformers, to train a multilanguage model. For this reason I was trying to take a look on the pipeline for Multi-language (https://nightly.spacy.io/models/xx) it is available on the list of compatibility for the 3.0.0 (https://github.com/explosion/spacy-models/blob/master/compatibility.json) but when I try to get it I get an error, it seems it is not available on the server. 
pipenv run python3.7 -m spacy download xx_ent_wiki_sm
Collecting xx_ent_wiki_sm==3.0.0a0
  ERROR: HTTP error 404 while getting https://github.com/explosion/spacy-models/releases/download/xx_ent_wiki_sm-3.0.0a0/xx_ent_wiki_sm-3.0.0a0.tar.gz#egg=xx_ent_wiki_sm==3.0.0a0
ERROR: Could not install requirement xx_ent_wiki_sm==3.0.0a0 from https://github.com/explosion/spacy-models/releases/download/xx_ent_wiki_sm-3.0.0a0/xx_ent_wiki_sm-3.0.0a0.tar.gz#egg=xx_ent_wiki_sm==3.0.0a0 because of HTTP error 404 Client Error: Not Found for url: https://github.com/explosion/spacy-models/releases/download/xx_ent_wiki_sm-3.0.0a0/xx_ent_wiki_sm-3.0.0a0.tar.gz for URL https://github.com/explosion/spacy-models/releases/download/xx_ent_wiki_sm-3.0.0a0/xx_ent_wiki_sm-3.0.0a0.tar.gz#egg=xx_ent_wiki_sm==3.0.0a0

Best regards,

-- Daniel

**Comment by adrianeboyd** [comment]
We're still working on getting everything configured to train the `xx` models in v3. Hopefully it will be available with the next rc release. The included NER model isn't going to be a transformer model, though, just a basic built-in CNN model.

If you want to train a multilanguage transformer model, just use lang `xx` (or whichever tokenizer makes sense) and specify a multilanguage tranformer model. Because `spacy init config` doesn't have a suggested transformer model for `xx`, you can initially choose English and then update `nlp.lang` and `components.transformer.model.name` in the config file to to the settings you'd like to use:

```
spacy init config -l en -o accuracy -p ner config.cfg
```

If you have `spacy-transformers` installed, this should automatically add a `transformer` component and set it to `roberta-base` for English. Just edit it the config however you'd like!
