### ISSUE TITLE
Support all output features

### ISSUE THREAD

**Issue by honnibal** [explosion/spacy-transformers#3]
Currently the `with_length_batching` and `foreach_sentence` functions don't handle the other outputs -- they only pass through the `last_hidden_states` features.

Support for the other features should mostly require updates to the `pad_batch_activations` and `Activations.split` functions.

**Comment by honnibal** [comment]
Pooler output now supported correctly. All hidden states and all attentions still to come.

**Comment by brendanchambers** [comment]
Came here to report that the all_hidden_states output is not supported. Seeing that it is a known issue. Thank you for your work!

**Comment by sergicastellasape** [comment]
Is there any update on this issue? `trf_all_hidden_states` output is still not supported if I'm not mistaken. When I call the attribute it returns a `NoneType` object. I thought the documentation on the README was a bit confusing, as they mention this as if it was already implemented!

**Comment by svlandeg** [comment]
I think this issue is not relevant anymore after the rewrite and recent publication of v1.0? I'll close this for now. 

New bugs can be opened on the [spaCy GitHub tracker](https://github.com/explosion/spaCy/issues) and feature requests or ask for coding help can be posted on the [spaCy discussions forum](https://github.com/explosion/spaCy/discussions)!
