### ISSUE TITLE
Unsupervised fine-tuning of language model (without head)?

### ISSUE THREAD

**Issue by tsoernes** [explosion/spacy-transformers#7]
Is it possible to do unsupervised fine-tuning of just the language model, without a head? As is sometimes the case, you've got lot's of domain specific unlabelled data and a much smaller amount of labelled data. Thus unsupervised fine-tuning is useful.

**Comment by honnibal** [comment]
I'd like to have an API for this in the library, but we don't currently. That said, using the `pytorch_transformers` code for it shouldn't be too much work -- they have some examples: https://github.com/huggingface/pytorch-transformers/tree/master/examples/lm_finetuning

You can get the `BertModel` instance out with:

```python

tok2vec = nlp.get_pipe("pytt_tok2vec")
bert_model = tok2vec.model._model
```

From there you could perform the LM fine-tuning following their script. Another approach would be to use their script exactly in order to complete the fine-tuning, and then repackage your own model. See the `examples/init_model.py` command for that.
