### ISSUE TITLE
How to use BERT Embeddings for keras models?

### ISSUE THREAD

**Issue by kommerzienrat** [explosion/spacy-transformers#85]
I used spacy-tranformers to turn documents into Bert vectors using e.g. `doc[0].vector`.
Is this the right way?

Moreover, as BERT is context-sensitive, I built an embedding matrix for my keras model for which the corresponding integer values are unique (first token of first training sample receives index 1, second 2, if the first word of the second sample is the 25th word in total (combined with the first sample, it receives index 25 etc.). This, however, enables me to train my model. But how can I make use of BERT embeddings when I want to train a new model, as the embeddings are context sensitive and cannot be look up in an embedding matrix / dictionary?

Embedding matrix:

```
bert_embedding_matrix = list()
X_berted = list()

'''
As BERT is context-based, every token may be individual and requires an OWN
INDEX value. It startes with one (1) in order to use zero (0) for padding.
'''
i = 1
for e in X_bert_vec:    
    var = list()
    for matrix in e:
        var.append(i)
        bert_embedding_matrix.append(matrix)
        i += 1
    X_berted.append(var)
    del var

bert_embedding_matrix = np.array(bert_embedding_matrix)
```

The model receives the input like this:

```
inp = Input(shape=(max_length,))#max_length
model = Embedding(input_dim=bert_embedding_matrix.shape[0], 
                                   output_dim=bert_embedding_matrix.shape[1],
                                    weights=[bert_embedding_matrix],
                                    trainable=False)(inp)
```

Or am I totally wrong here and spacy-transformers is not intended to be used like this?
Many thanks in advance.

**Comment by plison** [comment]
I don't think that providing a matrix when building the model is a good approach -- as you said, the whole point of BERT is to provide context-sensitive embeddings. The easiest is is to provide the embeddings at runtime.  That is:

```
#Notice we provide here a matrix, not a sequence of indices
input = Input(shape=(max_lengh, embedding_lengh), dtype=np.float32)  
...
```

This means that, instead of providing sequences of integers to your model, you will provide a tensor of context-sensitive embeddings computed via BERT.  If you are dealing with a relatively large training set, I recommend you use `fit_generator` to loop on your training data, and run BERT on batches of text.

**Comment by kommerzienrat** [comment]
It works -- thank you!
